server:
  port: 8081
app:
  ai:
    provider: openai #or any other AI provider
spring:
  application:
    name: genai-java-spring
  ai:
    docker-runner:
      api-key: dunny-string
      base-url: http://localhost:12434/engines/llama.cpp
      model: ai/smollm2
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.groq.com/openai/v1/chat/completions
      chat:
        options:
          model: openai/gpt-oss-20b #gpt-4o
    openrouter:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      model: nex-agi/nex-n2-pro:free
    vertex:
      ai:
        gemini:
          project-id: my-genai-project-123
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash

    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url: https://n7fadgaq8kbrw1n0.us-east-1.aws.endpoints.huggingface.cloud
        options:
          model: Qwen/Qwen2.5-Coder-7B-Instruct
          max-new-tokens: 1024
          temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: customer-mistral-model:latest
          #max-new-tokens: 512
          #temperature: 0.7







  logging:
    level:
      root: INFO
      com.genai.java.spring: INFO
      arg.springframwoek.ai: INFO

